"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "ru" | "en"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  ru: {
    // Общие
    dashboard: "Панель управления",
    profile: "Профиль",
    tasks: "Задачи",
    team: "Команда",
    wiki: "База знаний",
    analytics: "Аналитика",
    settings: "Настройки",
    search: "Поиск...",
    today: "сегодня",
    welcome: "Добро пожаловать",
    select_period: "Выберите период",
    select_club: "Выберите клуб",
    day: "День",
    week: "Неделя",
    month: "Месяц",
    quarter: "Квартал",
    year: "Год",
    all_locations: "Все локации",
    total_revenue: "Общая выручка",
    sales_count: "Количество продаж",
    vision_tests: "Проверки зрения",
    conversion_rate: "Конверсия",
    from_last_month: "по сравнению с прошлым месяцем",

    // Хедер
    notifications: "Уведомления",
    messages: "Сообщения",
    my_account: "Мой аккаунт",
    logout: "Выйти",
    view_all_notifications: "Просмотреть все уведомления",
    new_comment: "Новый комментарий к задаче",
    commented_on_task: "прокомментировала вашу задачу",
    minutes_ago: "минут назад",
    new_team_meeting: "Новая встреча команды",
    team_meeting_scheduled: "Запланирована встреча команды на завтра",
    hour_ago: "час назад",
    project_update: "Обновление проекта",
    updated_project_status: "обновил статус проекта",
    hours_ago: "часа назад",

    // Сообщения
    recent: "Недавние",
    unread: "Непрочитанные",
    search_messages: "Поиск сообщений...",
    online: "Онлайн",
    type_message: "Введите сообщение...",
    add_attachment: "Добавить вложение",
    video_call: "Видеозвонок",
    voice_call: "Голосовой звонок",
    close: "Закрыть",

    // Дашборд
    recent_tasks: "Недавние задачи",
    view_all: "Просмотреть все",
    upcoming_events: "Предстоящие события",
    view_calendar: "Просмотреть календарь",
    current_shift: "Текущая смена",
    view_all_team: "Просмотреть всех",
    team_activity: "Активность команды",
    metric_details: "Детали показателя",
    current_value: "Текущее значение",
    dynamics: "Динамика",
    comparison_with_last_year: "Сравнение с прошлым годом",
    forecast: "Прогноз",
    growth_expected: "Ожидается рост на 5-7% в следующем месяце",
    go_to_analytics: "Перейти к аналитике",
    compared_to_same_period: "+15.3% по сравнению с аналогичным периодом прошлого года",
    decline: "Отклонить",
    accept: "Принять",
    employee_profile: "Профиль сотрудника",
    contact_info: "Контактная информация",
    email: "Email",
    phone: "Телефон",
    performance_metrics: "Показатели эффективности",
    customer_rating: "Клиентская оценка",
    per_month: "за месяц",
    work_schedule: "График работы",
    tomorrow: "Завтра",
    send_message: "Отправить сообщение",
    full_profile: "Полный профиль",

    // Аналитика
    analytics: "Аналитика",
    business_performance: "Анализ продаж и эффективности бизнеса",
    export: "Экспорт",
    filters: "Фильтры",
    compared_to_last: "по сравнению с прошлым",
    sales: "Продажи",
    customers: "Клиенты",
    products: "Продукты",
    staff: "Персонал",
    sales_dynamics: "Динамика продаж",
    sales_comparison: "Сравнение продаж за выбранный период",
    top_products: "Топ продуктов",
    best_selling_products: "Самые продаваемые товары",
    customer_analysis: "Анализ клиентов",
    customer_behavior: "Информация о клиентах и их поведении",
    product_analysis: "Анализ продуктов",
    product_sales_info: "Информация о продуктах и их продажах",
    staff_analysis: "Анализ персонала",
    staff_performance: "Информация о работе персонала",
    select_period_location: "Выберите период и локацию для просмотра данных",
    sales_by_category: "Распределение продаж по категориям",
    sales_category_percentage: "Процентное соотношение продаж по категориям товаров",
    marketing_effectiveness: "Эффективность маркетинговых кампаний",
    marketing_results: "Анализ результатов маркетинговых активностей",
    data_loading: "Данные загружаются...",

    // Профиль
    profile_job_title: "Управляющая компания - Senior UX Designer",
    current_projects: "Текущие проекты",
    website_redesign: "Редизайн веб-сайта",
    mobile_app_design: "Дизайн мобильного приложения",
    in_progress: "В процессе",
    planning: "Планирование",
    kpis: "KPI",
    projects_completed: "Завершенные проекты",
    task_completion_rate: "Коэффициент выполнения задач",
    team_satisfaction: "Удовлетворенность команды",
    project_roles: "Роли в проектах",
    lead_designer: "Ведущий дизайнер",
    ux_consultant: "UX-консультант",
    active: "Активно",
    skills_expertise: "Навыки и экспертиза",
    ui_design: "UI дизайн",
    ux_research: "UX исследования",
    prototyping: "Прототипирование",
    design_systems: "Дизайн-системы",
    user_testing: "Пользовательское тестирование",

    // Задачи
    new_franchise_location: "Настройка новой франшизы",
    jan_15_2025: "15 янв 2025",
    mar_30_2025: "30 мар 2025",
    overall_progress: "Общий прогресс",
    tasks_completed: "Выполнено задач",
    days_remaining: "Осталось дней",
    team_members: "Участники команды",
    integration: "Интеграция",
    setup: "Настройка",
    launch: "Запуск",
    completed: "Завершено",
    pending: "Ожидание",
    site_selection: "Выбор места",
    budget_approval: "Утверждение бюджета",
    lease_agreement: "Договор аренды",
    permits_licenses: "Разрешения и лицензии",
    equipment_installation: "Установка оборудования",
    staff_training: "Обучение персонала",
    marketing_campaign: "Маркетинговая кампания",
    grand_opening: "Торжественное открытие",
    add_task_to_phase: "Добавить задачу в фазу",
    current_tasks: "Текущие задачи",
    task: "Задача",
    start_date: "Дата начала",
    due_date: "Срок выполнения",
    status: "Статус",
    actions: "Действия",
    view: "Просмотр",
    sign_lease_agreement: "Подписать договор аренды",
    not_started: "Не начато",
    it_systems_setup: "Настройка IT-систем",
    high_priority: "Высокий приоритет",
    it_systems_manager: "IT-системный менеджер",
    configure_erp: "Настройка доступа к ERP-системе (Itigris) для сотрудников клуба",
    install_pos: "Установка и настройка POS-системы и интеграция с ERP и CRM",
    connect_medical_equipment:
      "Подключение и синхронизация офтальмологического медицинского оборудования с медицинским ПО",
    description: "Описание",
    resources: "Ресурсы",
    setup_guides: "Руководства по настройке",
    video_tutorials: "Видеоуроки",
    it_support: "IT-поддержка",
    wiki_documentation: "Wiki-документация",
    checklist: "Чек-лист",
    initial_system_requirements: "Первоначальный анализ системных требований",
    erp_configuration: "Настройка ERP-системы",
    pos_integration: "Интеграция POS-системы",
    attachments: "Вложения",
    add_attachment: "Добавить вложение",
    comments: "Комментарии",
    add_comment: "Добавить комментарий",
    post_comment: "Опубликовать комментарий",
    assignee: "Исполнитель",
    timeline: "Временная шкала",
    progress: "Прогресс",
    completion: "Завершение",
    complete: "завершено",
    edit: "Редактировать",
    add_task: "Добавить задачу",
    add_new_task: "Добавить новую задачу",
    title: "Название",
    phase: "Фаза",
    priority: "Приоритет",
    high: "Высокий",
    medium: "Средний",
    low: "Низкий",
    cancel: "Отмена",
    create_task: "Создать задачу",
    add_checklist_item: "Добавить пункт чек-листа",
    started: "Начало",
    due: "Срок",

    // Языки
    language: "Язык",
    english: "English",
    russian: "Русский",

    // Новый клуб
    new_club: "Новый клуб",
    new_club_opening_process: "Процесс открытия клуба оптики Loov",
    total_duration: "Общая продолжительность",
    "13_25_weeks": "13-25 недель (3-6 месяцев)",
    export_plan: "Экспорт плана",
    start_new_project: "Начать новый проект",
    project_progress: "Прогресс проекта",
    overall_completion: "Общее выполнение",
    current_process: "Текущий процесс",
    improved_process: "Улучшенный процесс",
    current_club_opening_process: "Текущий процесс открытия клуба оптики Loov",
    improved_club_opening_process: "Улучшенный процесс открытия клуба оптики Loov",
    improved_process_coming_soon: "Улучшенный процесс в разработке",
    stage_1_preparation: "ЭТАП 1: ПОДГОТОВКА",
    stage_2_construction: "ЭТАП 2: СТРОИТЕЛЬНО-МОНТАЖНЫЕ РАБОТЫ",
    stage_3_opening_preparation: "ЭТАП 3: ПОДГОТОВКА К ОТКРЫТИЮ",
    stage_4_launch: "ЭТАП 4: ЗАПУСК",
    "3_6_weeks": "3-6 недель",
    "6_12_weeks": "6-12 недель",
    "2_4_weeks": "2-4 недели",
    "2_3_weeks": "2-3 недели",
    ceo_management: "CEO / Руководство",
    operations_manager: "Операционный менеджер",
    creative_manager: "Креативный менеджер",
    designer: "Дизайнер",
    it_specialist: "IT-специалист",
    hr_recruiter: "HR / Рекрутер",
    legal: "Юрист",
    marketing: "Маркетинг",
    project_initiation: "Инициирование проекта",
    location_search: "Поиск и отбор помещения",
    tender_launch: "Запуск тендеров",
    legal_lease_check: "Юридическая проверка аренды",
    design_concept: "Разработка дизайн-концепции",
    staff_planning: "Планирование персонала",
    unique_items_search: "Поиск уникальных предметов",
    construction_control: "Контроль строительных работ",
    equipment_purchase: "Закупка оборудования",
    demolition_rough_finish: "Демонтаж и черновая отделка",
    electrical_wiring: "Прокладка электрики",
    ventilation_installation: "Монтаж вентиляции",
    finishing_work: "Чистовая отделка",
    site_acceptance: "Приемка объекта",
    author_supervision: "Авторский надзор",
    network_design: "Проектирование сетей",
    furniture_arrangement: "Расстановка мебели",
    equipment_setup: "Настройка оборудования",
    staff_hiring: "Найм персонала",
    obtaining_licenses: "Получение лицензий",
    pre_launch_campaign: "Предстартовая кампания",
    soft_opening: "Soft Opening",
    process_adjustment: "Отладка процессов",
    review_management: "Работа с отзывами",
    results_analysis: "Анализ результатов",
    task_info: "Информация о задаче",
    executor: "Исполнитель",
    approver: "Согласующий",
    deadline: "Сроки",
    reference_info: "Справочная информация",
    add_comment_placeholder: "Добавьте комментарий...",
    save_progress: "Сохранить прогресс",
    key_responsibilities: "Основные задачи",
    "1_2_weeks": "1-2 недели",
    "5_working_days": "5 рабочих дней",
    "1_week": "1 неделя",
    ongoing: "Постоянно",
    "2_3_weeks_after_opening": "2-3 недели после открытия",
    board_of_directors: "Совет директоров",
    ceo_legal: "CEO / Юрист",
    ceo: "CEO",
    ceo_ops: "CEO / Ops",
    ceo_creative: "CEO / Креативный менеджер",
    develop_business_plan: "Разработать бизнес-план",
    determine_project_budget: "Определить бюджет проекта",
    form_project_team: "Сформировать проектную команду",
    approve_club_concept: "Утвердить концепцию клуба",
    define_success_criteria: "Определить критерии успеха",
    project_initiation_desc: "Определение основных параметров проекта и формирование команды.",
    project_initiation_ref: "Важно определить четкие KPI и сроки для всего проекта.",
  },
  en: {
    // Common
    dashboard: "Dashboard",
    profile: "Profile",
    tasks: "Tasks",
    team: "Team",
    wiki: "Knowledge Base",
    analytics: "Analytics",
    settings: "Settings",
    search: "Search...",
    today: "today",
    welcome: "Welcome",
    select_period: "Select period",
    select_club: "Select club",
    day: "Day",
    week: "Week",
    month: "Month",
    quarter: "Quarter",
    year: "Year",
    all_locations: "All locations",
    total_revenue: "Total Revenue",
    sales_count: "Sales Count",
    vision_tests: "Vision Tests",
    conversion_rate: "Conversion Rate",
    from_last_month: "from last month",

    // Header
    notifications: "Notifications",
    messages: "Messages",
    my_account: "My Account",
    logout: "Logout",
    view_all_notifications: "View all notifications",
    new_comment: "New comment on task",
    commented_on_task: "commented on your task",
    minutes_ago: "minutes ago",
    new_team_meeting: "New team meeting",
    team_meeting_scheduled: "Team meeting scheduled for tomorrow",
    hour_ago: "hour ago",
    project_update: "Project update",
    updated_project_status: "updated project status",
    hours_ago: "hours ago",

    // Messages
    recent: "Recent",
    unread: "Unread",
    search_messages: "Search messages...",
    online: "Online",
    type_message: "Type a message...",
    add_attachment: "Add attachment",
    video_call: "Video call",
    voice_call: "Voice call",
    close: "Close",

    // Dashboard
    recent_tasks: "Recent Tasks",
    view_all: "View all",
    upcoming_events: "Upcoming Events",
    view_calendar: "View calendar",
    current_shift: "Current Shift",
    view_all_team: "View all",
    team_activity: "Team Activity",
    metric_details: "Metric Details",
    current_value: "Current Value",
    dynamics: "Dynamics",
    comparison_with_last_year: "Comparison with Last Year",
    forecast: "Forecast",
    growth_expected: "Expected growth of 5-7% next month",
    go_to_analytics: "Go to Analytics",
    compared_to_same_period: "+15.3% compared to the same period last year",
    decline: "Decline",
    accept: "Accept",
    employee_profile: "Employee Profile",
    contact_info: "Contact Information",
    email: "Email",
    phone: "Phone",
    performance_metrics: "Performance Metrics",
    customer_rating: "Customer Rating",
    per_month: "per month",
    work_schedule: "Work Schedule",
    tomorrow: "Tomorrow",
    send_message: "Send Message",
    full_profile: "Full Profile",

    // Analytics
    analytics: "Analytics",
    business_performance: "Sales and business performance analysis",
    export: "Export",
    filters: "Filters",
    compared_to_last: "compared to last",
    sales: "Sales",
    customers: "Customers",
    products: "Products",
    staff: "Staff",
    sales_dynamics: "Sales Dynamics",
    sales_comparison: "Sales comparison for the selected period",
    top_products: "Top Products",
    best_selling_products: "Best selling products",
    customer_analysis: "Customer Analysis",
    customer_behavior: "Information about customers and their behavior",
    product_analysis: "Product Analysis",
    product_sales_info: "Information about products and their sales",
    staff_analysis: "Staff Analysis",
    staff_performance: "Information about staff performance",
    select_period_location: "Select period and location to view data",
    sales_by_category: "Sales Distribution by Category",
    sales_category_percentage: "Percentage distribution of sales by product categories",
    marketing_effectiveness: "Marketing Campaign Effectiveness",
    marketing_results: "Analysis of marketing activities results",
    data_loading: "Data loading...",

    // Profile
    profile_job_title: "Company Management - Senior UX Designer",
    current_projects: "Current Projects",
    website_redesign: "Website Redesign",
    mobile_app_design: "Mobile App Design",
    in_progress: "In Progress",
    planning: "Planning",
    kpis: "KPIs",
    projects_completed: "Projects Completed",
    task_completion_rate: "Task Completion Rate",
    team_satisfaction: "Team Satisfaction",
    project_roles: "Project Roles",
    lead_designer: "Lead Designer",
    ux_consultant: "UX Consultant",
    active: "Active",
    skills_expertise: "Skills & Expertise",
    ui_design: "UI Design",
    ux_research: "UX Research",
    prototyping: "Prototyping",
    design_systems: "Design Systems",
    user_testing: "User Testing",

    // Tasks
    new_franchise_location: "New Franchise Location Setup",
    jan_15_2025: "Jan 15, 2025",
    mar_30_2025: "Mar 30, 2025",
    overall_progress: "Overall Progress",
    tasks_completed: "Tasks Completed",
    days_remaining: "Days Remaining",
    team_members: "Team Members",
    integration: "Integration",
    setup: "Setup",
    launch: "Launch",
    completed: "Completed",
    pending: "Pending",
    site_selection: "Site Selection",
    budget_approval: "Budget Approval",
    lease_agreement: "Lease Agreement",
    permits_licenses: "Permits & Licenses",
    equipment_installation: "Equipment Installation",
    staff_training: "Staff Training",
    marketing_campaign: "Marketing Campaign",
    grand_opening: "Grand Opening",
    add_task_to_phase: "Add task to phase",
    current_tasks: "Current Tasks",
    task: "Task",
    start_date: "Start Date",
    due_date: "Due Date",
    status: "Status",
    actions: "Actions",
    view: "View",
    sign_lease_agreement: "Sign Lease Agreement",
    not_started: "Not Started",
    it_systems_setup: "IT Systems Setup",
    high_priority: "High Priority",
    it_systems_manager: "IT Systems Manager",
    configure_erp: "Configure ERP system (Itigris) access for club employees",
    install_pos: "Install and configure the POS system and ensure integration with ERP and CRM",
    connect_medical_equipment: "Connect and synchronize ophthalmological medical equipment with healthcare software",
    description: "Description",
    resources: "Resources",
    setup_guides: "Setup Guides",
    video_tutorials: "Video Tutorials",
    it_support: "IT Support",
    wiki_documentation: "Wiki Documentation",
    checklist: "Checklist",
    initial_system_requirements: "Initial system requirements analysis",
    erp_configuration: "ERP system configuration",
    pos_integration: "POS system integration",
    attachments: "Attachments",
    add_attachment: "Add Attachment",
    comments: "Comments",
    add_comment: "Add a comment...",
    post_comment: "Post Comment",
    assignee: "Assignee",
    timeline: "Timeline",
    progress: "Progress",
    completion: "Completion",
    complete: "complete",
    edit: "Edit",
    add_task: "Add Task",
    add_new_task: "Add New Task",
    title: "Title",
    phase: "Phase",
    priority: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    cancel: "Cancel",
    create_task: "Create Task",
    add_checklist_item: "Add checklist item",
    started: "Started",
    due: "Due",
    develop_business_plan: "Develop business plan",
    determine_project_budget: "Determine project budget",
    form_project_team: "Form project team",
    approve_club_concept: "Approve club concept",
    define_success_criteria: "Define success criteria",
    project_initiation_desc: "Definition of the main project parameters and team formation.",
    project_initiation_ref: "It is important to define clear KPIs and deadlines for the entire project.",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("ru")

  useEffect(() => {
    // Проверяем сохраненный язык в localStorage
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "ru" || savedLanguage === "en")) {
      setLanguage(savedLanguage)
    }
  }, [])

  const changeLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>{children}</LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
